### ISSUE TITLE
Status nach Abmeldung von Prüfung

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#17]
In der APP ist nach Abmeldung von einer Prüfung nicht erkennbar ob diese angekommen ist.

**Comment by HTWDD** [comment]
Was meinst du mir "angekommen", die Darstellung in der App von abgemeldeten Prüfungen?

Kannst du mir bitte ein JSON-Beispiel für eine abgemeldete Prüfung schicken? Die JSON-Daten bekommst du von hier: https://www2.htw-dresden.de/~s71513/API/
Die erste Abfrage liefert dir dabei die Werte für die zweite, in dieser sind dann deine Noten enthalten.

**Comment by s72785** [comment]
Die Darstellung ob man erfolgreich abgemeldet ist.
Ich kann das nicht direkt weil ich mich nicht abgemeldet hatte, habe das nur von Commilitonen mitbekommen. Werde die aber mal anschreiben.
