### ISSUE TITLE
Doku: Schnittstellenbeschreibung

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#19]
Es wäre gut die Daten-Schnittstellen statt nur durch Code auch in Doku zu beschreiben bzw. Zugänglichkeit zu erhöhen.
Vorschlag: Ausgabe von JSON bei raiplan usw.

**Comment by FestPlatin** [comment]
Die Schnittstellen haben seit einiger Zeit ein eigenes Repository (https://github.com/HTWDD/Webservices) in diesem ist auch ein Wiki enthalten welches die Benutzung dokumentiert.
