### ISSUE TITLE
Doku: Howto get started - Installing IDE

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#20]
Weil hier ja schon wieder ein paar Monate Ruhe ist und demnächst andere Java lernen sollen und ggf. das ein oder andere beitragen könnten...

Was braucht es um hier beitragen zu können?
Wie installiere ich eine IDE die mit euren Dateien loslegen kann?

**Comment by HTWDD** [comment]
Für Java-Anfänger ist das Projekt eher nicht geeignet. Gedacht ist es vor allem für die Studenten des Faches "Mobile Netze". Es darf aber trotzdem jeder seinen Beitrag dazu beitragen.

Ich habe im Wiki einen kleinen Eintrag dazu erstellt, der Import ist dann eigentlich selbsterklärend.
