### ISSUE TITLE
Sprachen unterstützen

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#21]
Idee: Mehrsprachichkeit unterstützen
- Strings mit lang Attributen versehen um ggf. künftig andere Sprachen (insb. English) zu ergänzen
- Auswahl für Sprachen ermöglichen, Standard bleibt Deutsch

**Comment by HTWDD** [comment]
Bis jetzt gibt es noch keinen konkreten Plan mehrere Sprachen zu unterstützen.

Es wird allerdings schon versucht Strings immer in die entsprechenden Ressourcen-Dateien auszulagern. Ein spezielles lang-Attribute muss aber in Android nicht vergeben werden, das geht eleganter.

**Comment by FestPlatin** [comment]
Diese App wird eingestellt.
