### ISSUE TITLE
Architektur: Semester-/Stundenplan-Parsing auf Server auslagern

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#22]
Für mobile Apps ist es nicht wirklich hilfreich wenn die Daten gesammelt abgefragt werden und dann auch noch auf der schwachbrüstigen Plattform verarbietet werden müssen.
Daher: Parsing auf Server-Seite erledigen lassen. Ist hier auch unproblematisch, da es sich um keine schützenswerten Daten handelt.

Vorteile
* Das spart Traffic
* senkt die Fehleranfälligkeit
* erhöht die Wartbarkeit, da Fehlerbehebung kein neues App-Deployment erfordert
* barriereärmer: weitere Anwendungen können die gleichen Daten leichter nutzen
* geringere Abhängigkeit von einer Datenquelle, Definition einer Schnittstelle die künftig direkt bedient werden kann

Soweit ich das sehe... (z.B. in StundenplanFragment.java )

* Derzeit: rawa's PHP liefert HTML ohne hübsche IDs oder CLASSen, HTML wird von Apps umständlich geparsed, in Datentypen geschoben und dann ausgegeben.
* Daten-/Schnittstellen definitieren: direkt maschinenlesbar, transparenter und barrierefreier, z.B. mit JSON
* Ziel: Auslieferung von sauber maschinenlesbaren Daten durch Server, App muss nur noch in den Datentyp transformieren und anzeigen.

**Comment by HTWDD** [comment]
Die Vorteile sind mir durchaus bewusst und ich arbeite auch bereits daran dies zu ändern. So wurde bereits die Notenabfrage und die Prüfungstermine auf eine neue API umgestellt.

Zum Stundenplan kann ich nur sagen, das dies alles noch Code von Mark Schramm ist. Solange es keine API zur Abfrage gibt, wird sich daran auch nicht viel ändern.

Das erstellen der API's ist auch nicht von heute auf morgen erledigt. Vorallem da es keinen ordenlichen Schnittstellen / Daten gibt mit denen man arbeiten kann.

**Comment by s72785** [comment]
Der Vorteil wenn es noch keiner vorgibt ist ja, dass man alle Freiheiten hat. Wie hättest du die Daten denn gerne? Ich habe jetzt erstmal nur so in Blaue hinein phantasiert um es plastisch zu verargumentieren,

**Comment by HTWDD** [comment]
Zur Ausgabe an die App gerne in JSON^^
Dazu müssen wir die Daten aber erst mal selbst ordentlich parsen, da gibt es leider keinen Weg daran vorbei :(

**Comment by s72785** [comment]
ja, erstmal Ziel definieren und dann betanken.. ich schriebe mal was und erhoffe mir korrektiv, fork in progress

**Comment by HTWDD** [comment]
Was möchtest du genau schreiben? Das parsen der Daten oder bereits eine Definition der API?

**Comment by s72785** [comment]
erstmal die schemata (Zieldefinition für die API).. dann ein Script für die API das eine entsprechende Ausgabe produziert, dabei müssen wir uns noch über die Parameter klar werden um nur optional Dinge abzufragen die - normalerweise oder noch - keiner wissen möchte.. und wenn das dann mal abgehangen ist, kannst du as evtl. einbauen :) nur keine verfrühte Eile
Heute dann mal recherche zu recurring wegen der Daten für ical etc., das wird noch für andere Dinge interessant.

**Comment by s72785** [comment]
backend scheint ja genutzt zu werden, doku fehlt(?)
