### ISSUE TITLE
UTF8 deprecated?! HTWDD/src/de/htwdd/classes/HTTPDownloader.java

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#26]
Sollte UTF8 nicht das Standard-Encoding sein anstatt anders herum?

**Comment by HTWDD** [comment]
Die Funktionsnamen hatten nichts mit der jeweiligen Standardverwendung zu tun. Die sind noch von meinen Vorgänger so gewählt wurden.

**Comment by s72785** [comment]
ich sehe gerade, dass garnicht analysiert wird, welches Encoding tatsächlich vorliegt.
Hat HTTPdownloader eine Eigenschaft, bei der das Encoding aus der Antwort heraus mitgeliefert wird? (oder so ähnlich..) Dann könnte man das Quellenneutral verzweigt implementieren.
Das wäre aus meiner Sicht ein wichtiger Schritt zur dynamisierung der Datenquellen oder falls eine Quelle mal was neu macht.

**Comment by HTWDD** [comment]
Ich habe dazu leider nichts gefunden. Bis auf die Mensa nutzen alle Schnittstellen auch UTF-8 als Encoding.

**Comment by s72785** [comment]
eventuell geht was wie (http://stackoverflow.com/questions/18046505/how-can-i-change-charset-encoding-in-http-response-in-java)
 httppost.setHeader("Accept-Encoding","UTF-8"); 

aber ich habe noch nicht gesehen wo man das gelieferte encoding mal angesagt bekommt, das wäre das was man wissen will. Villeicht ist HTTP schon wieder zu weit weggekapselt.

**Comment by s72785** [comment]
gefunden: URLConnection.getContentEncoding() liefert das gewünschte wonach man auch ohne Vergleich von umgewandelten Kopien verzweigen könnte.

**Comment by HTWDD** [comment]
Nein tut es nicht.
Laut Beschreibung: "*Returns the content encoding type specified by the response header field content-encoding or null if this field is not set.*" Es würde schon das richtige zurückgeben, wenn das Feld gesetzt wäre, dies ist aber nicht der Fall.
Zuverlässigere Aussagen würde dann eher `URLConnection.getContentType()` geben, aus welchen man dann das charset rausparsen könnte. Aber dies muss auch nicht gesetzt sein.

**Comment by s72785** [comment]
dann kann man das wohl nur opportunistisch durchexerzieren und im schlimmsten fall utf8encode(string)==string prüfen und weiß dann ob das original utf8 war etc. pp
Schade, dachte die Klasse kann das schon so. Encoding is halt son Thema für sich (s.a. letzets Pentaradio)
