### ISSUE TITLE
Integration des StuRa-Infos etc.

### ISSUE THREAD

**Issue by Nos-** [HTWDD/HTWDD#28]
Die Onlinedienste des StuRa und der anderen Gremien der studentischen Selbstverwaltung sollten ebenfalls in der App integriert sein. Besonders sinnvoll erscheinen mir folgende:
- Newsfeed
- Kalender (sofern vorhanden und exportierbar)
- Link auf Homepage, Wiki etc.

**Comment by BenchR267** [comment]
Gute Idee, hast du spezielle Links zu den Quellen?

**Comment by Nos-** [comment]
Ja, hab ich.
* Hier die Homepage: http://stura.htw-dresden.de/
* und hier der Newsfeed: http://www.stura.htw-dresden.de/news/RSS

Einen Kalender gibts auf der Homepage auch, doch kann man die Termine leider nur einzeln in den eigenen Kalender importieren. Dennoch macht ein CalDav/ iCal-Import Sinn, da sowohl das Opal der Hochschule als auch das StuRa-OwnCloud es anbieten (und man dort prinzipiell auch seinen Stundenplan ablegen kann).
