### ISSUE TITLE
uncatched exceptions - warum?

### ISSUE THREAD

**Issue by s72785** [HTWDD/HTWDD#29]
z.B. in https://github.com/HTWDD/HTWDD/blob/0186eae0ab5a6b09e11e5637a19d2b08553fb745/src/de/htwdd/WizardStudyGroup.java - wahrscheinlich noch einige

Vorschlag: Ursache einschränken, Error-Reporting, ggf. Logs weitersenden wenn Nutzer einverstanden

**Comment by HTWDD** [comment]
Es handelt sich dabei noch alten, noch nicht (groß) überarbeiteten Code von Mark Schramm.
Error-Reporting wurde bereits in einer anderen App bereits getestet. Prinzipiell liegt aber jetzt der Fokus auf der Erstellung einer neuen App.

**Comment by FestPlatin** [comment]
Diese App wurde jetzt als deprecated markiert. Fehler werde ich zwar noch fixen aber keine neuen Sachen mehr einbauen. Wie bereits geschrieben liegt der Fokus auf der neuen App, daher schließe ich das Ticket erstmal.
